### ISSUE TITLE
mongo error on project from scratch

### ISSUE THREAD

**Issue by frenchrabbit** [mono-js/mono#14]
Created a project with create-mono-app (all options except elastic search).
```
[mono-dev] Starting project...
2018-07-09T14:19:56.641Z - debug: [test-api] Environment: development
2018-07-09T14:19:56.644Z - debug: [test-api] Loading conf/application.js configuration
2018-07-09T14:19:56.644Z - debug: [test-api] Loading conf/development.js configuration
2018-07-09T14:19:57.451Z - debug: [test-api] Boot mono-doc module
2018-07-09T14:19:57.984Z - debug: [test-api] Boot mono-mongodb module
2018-07-09T14:19:57.984Z - info: [test-api:mono-mongodb] Connecting to mongodb://localhost:27017...
(node:2966) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2018-07-09T14:19:58.015Z - info: [test-api:mono-mongodb] Connected to test-api database
/Users/user/Projects/test-api/node_modules/mono-core/lib/index.js:38
	throw err
	^

TypeError: Cannot read property 'mongodb' of undefined
    at Object.<anonymous> (/Users/user/Projects/test-api/node_modules/mono-mongodb/lib/utils.js:7:53)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/user/Projects/test-api/node_modules/mono-mongodb/lib/index.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

```

**Comment by gaetansenn** [comment]
Hello @frenchrabbit did you added the mono.mongodb config as mentioned in the README https://github.com/mono-js/mono-mongodb#configuration

Regards,
