### ISSUE TITLE
Issue with deployment on heroku

### ISSUE THREAD

**Issue by vsage** [mono-js/mono#15]
Hello,

I've built a small app with mono, using basic routes and controllers. I've filled the production.js like this:

`module.exports = {
	mono: {
		jwt: {
			secret: "xxxxxx"
		},
		http: {
			logLevel: 'combined'
		},
		log: {
			level: 'verbose'
		},
		mongodb: {
			url: 'mongodb://username:password@ds225382.mlab.com:25382',
			dbName: 'dbname'
		}
	}
}`

It's working locally with `npm start`, however when I deploy (Heroku) the app cannot start because conf.mono seems to be undefined (here are the server logs): 

`2018-08-19T20:55:04.322416+00:00 app[web.1]: /app/node_modules/mono-core/lib/index.js:38
2018-08-19T20:55:04.322419+00:00 app[web.1]: throw err
2018-08-19T20:55:04.322420+00:00 app[web.1]: ^
2018-08-19T20:55:04.322421+00:00 app[web.1]:
2018-08-19T20:55:04.322423+00:00 app[web.1]: TypeError: Cannot read property 'mongodb' of undefined
2018-08-19T20:55:04.322425+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/mono-mongodb/lib/utils.js:7:53)`

Do you have any idea on what could be wrong ?

Thank you.

Best

**Comment by Atinux** [comment]
Hi @vsage 

Do you have the logs about what configuration files is being loaded?

Make sure to add `NODE_ENV` `production` in your Heroku envs

**Comment by vsage** [comment]
Hi @Atinux,
Thanks for the answer, I've added NODE_ENV=production in my env config variables however it seems to output the same issue. Here are the complete logs on the issue:

`2018-08-20T15:49:22.231897+00:00 heroku[web.1]: Starting process with command `npm start`
2018-08-20T15:49:25.571827+00:00 app[web.1]:
2018-08-20T15:49:25.571858+00:00 app[web.1]: > expressio-server@0.0.1 start /app
2018-08-20T15:49:25.571860+00:00 app[web.1]: > cross-env NODE_ENV=production mono
2018-08-20T15:49:25.571862+00:00 app[web.1]:
2018-08-20T15:49:29.376931+00:00 app[web.1]: 2018-08-20T15:49:29.366Z - debug: [expressio-server] Environment: production
2018-08-20T15:49:29.381142+00:00 app[web.1]: 2018-08-20T15:49:29.380Z - debug: [expressio-server] Loading conf/application.js configuration
2018-08-20T15:49:29.386808+00:00 app[web.1]: 2018-08-20T15:49:29.386Z - debug: [expressio-server] Loading conf/production.js configuration
2018-08-20T15:49:36.577218+00:00 app[web.1]: 2018-08-20T15:49:36.576Z - debug: [expressio-server] Boot mono-doc module
2018-08-20T15:49:40.196543+00:00 app[web.1]: 2018-08-20T15:49:40.196Z - debug: [expressio-server] Boot mono-mongodb module
2018-08-20T15:49:40.200878+00:00 app[web.1]: 2018-08-20T15:49:40.200Z - info: [expressio-server:mono-mongodb] Connecting to mongodb://xxxxxxx:xxxxxxxx@ds225382.mlab.com:25382/expressio...
2018-08-20T15:49:40.393872+00:00 app[web.1]: (node:26) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2018-08-20T15:49:40.770517+00:00 app[web.1]: 2018-08-20T15:49:40.770Z - info: [expressio-server:mono-mongodb] Connected to expressio database
2018-08-20T15:49:40.805715+00:00 app[web.1]: /app/node_modules/mono-core/lib/index.js:38
2018-08-20T15:49:40.805720+00:00 app[web.1]: throw err
2018-08-20T15:49:40.805722+00:00 app[web.1]: ^
2018-08-20T15:49:40.805724+00:00 app[web.1]:
2018-08-20T15:49:40.805727+00:00 app[web.1]: TypeError: Cannot read property 'mongodb' of undefined
2018-08-20T15:49:40.805729+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/mono-mongodb/lib/utils.js:7:53)`

It seems to be able to read applications.js and production.js but stops on mono-mongodb loading (even if it manages to connect to the db)

thank you.

**Comment by vsage** [comment]
Hi @benjamincanac,

You update works like a charm, and there is no more issue with mono-mongodb. However now the server can't start because of a PORT issue. Here is the log from the server:

`2018-08-21T09:48:58.595086+00:00 app[web.1]: 2018-08-21T09:48:58.594Z - debug: [node-skeleton] Server running on http://localhost:11477`
`2018-08-21T09:48:58.596028+00:00 app[web.1]: 2018-08-21T09:48:58.595Z - info: [node-skeleton] Startup durationMs=2170`
`2018-08-21T09:49:52.190844+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch``

After investigating, this can be caused by listening to a fixed PORT (whereas heroku assigns it dynamically) however looking at the code, it seems that you don't do that.

Any idea on this would be appreciated,

Thanks!

Victor

**Comment by Atinux** [comment]
Try `HOST` `0.0.0.0`

**Comment by vsage** [comment]
@Atinux 

Thanks ! Everything works.
You should put it in the docs ;)

Best,

Victor

**Comment by atinux** [comment]
It's updated: https://mono.js.org/#/deploying?id=heroku

Thank you @vsage :)
